### ISSUE TITLE
NullPointerException on EventType

### ISSUE THREAD

**Issue by psykofatfat** [EXIficient/exificient#27]
Hi, 

i'm trying to decode an EXI file. 
The CodingMode is COMPRESSION mode, the EXI options contains the element `<compression />.`
When i try to decode the file, a NullPointerException occures when trying to parse the header element.
Here is the stacktrace :

java.lang.NullPointerException: Attempt to invoke virtual method 'int com.siemens.ct.exi.core.grammars.event.EventType.ordinal()' on a null object reference
	at com.siemens.ct.exi.core.coder.EXIBodyDecoderReordered.preReadBlockStructure(EXIBodyDecoderReordered.java:388)
	at com.siemens.ct.exi.core.coder.EXIBodyDecoderReordered.initForEachRun(EXIBodyDecoderReordered.java:194)
	at com.siemens.ct.exi.core.coder.EXIBodyDecoderReordered.setInputStream(EXIBodyDecoderReordered.java:240)
	at com.siemens.ct.exi.core.coder.EXIStreamDecoderImpl.decodeHeader(EXIStreamDecoderImpl.java:97)
	at com.siemens.ct.exi.main.api.sax.SAXDecoder.parse(SAXDecoder.java:246)
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)

The nextEventType is set to null in AbstractEXIBodyDecoder.decodeEventCode() at this step : 
`nextEventType = fidelityOptions.get3rdLevelEventType(ec3);`

Thanks for your help :)

**Comment by danielpeintner** [comment]
Hi,
do you have an example that allows me to reproduce the issue: I doubt that it is a valid EXI  file you are trying to decode (ot it used different coding options).

Anyhow, the NPE should not happen. Thanks 👍
