### ISSUE TITLE
Unhandled exception when attempting to decode

### ISSUE THREAD

**Issue by jadams-tresys** [EXIficient/exificient#33]
Ran into this issue when attempting to decode a schema aware encoded file without using a schema aware decoder:

java.lang.IllegalArgumentException
  | => dat java.lang.AbstractStringBuilder.appendCodePoint(AbstractStringBuilder.java:800)
        at java.lang.StringBuilder.appendCodePoint(StringBuilder.java:240)
	at com.siemens.ct.exi.core.io.channel.AbstractDecoderChannel.decodeStringOnlySupplementaryCodePoints(AbstractDecoderChannel.java:111)
	at com.siemens.ct.exi.core.io.channel.AbstractDecoderChannel.decodeStringOnly(AbstractDecoderChannel.java:89)
	at com.siemens.ct.exi.core.coder.AbstractEXIBodyDecoder.decodeLocalName(AbstractEXIBodyDecoder.java:170)
	at com.siemens.ct.exi.core.coder.AbstractEXIBodyDecoder.decodeQName(AbstractEXIBodyDecoder.java:133)
	at com.siemens.ct.exi.core.coder.AbstractEXIBodyDecoder.decodeStartElementGenericStructure(AbstractEXIBodyDecoder.java:484)
	at com.siemens.ct.exi.core.coder.EXIBodyDecoderInOrder.decodeStartElement(EXIBodyDecoderInOrder.java:126)
	at com.siemens.ct.exi.main.api.sax.SAXDecoder.parseEXIEvents(SAXDecoder.java:313)
	at com.siemens.ct.exi.main.api.sax.SAXDecoder.parse(SAXDecoder.java:250)
	at net.sf.saxon.resource.ActiveSAXSource.deliver(ActiveSAXSource.java:190)
	at net.sf.saxon.event.Sender.send(Sender.java:105)
	at net.sf.saxon.jaxp.IdentityTransformer.transform(IdentityTransformer.java:364)
	at org.apache.daffodil.Main$.runIgnoreExceptions(Main.scala:1307)
	at org.apache.daffodil.Main$.run(Main.scala:1433)
	at org.apache.daffodil.CLI.Util$CLIThread.run(Util.scala:281)

This eventually gets caught by Saxon, but in it's current version ends up getting printed out to stderr instead of passing the exception along to the caller.

**Comment by jadams-tresys** [comment]
Pull request created: https://github.com/EXIficient/exificient/pull/34

**Comment by danielpeintner** [comment]
Great, thanks!
#34 has been merged and a *new* snapshot version has been published, see https://oss.sonatype.org/content/repositories/snapshots/com/siemens/ct/exi/exificient/1.0.5-SNAPSHOT/
